version: "3"
services:
  casiplus-hapi-fhir-jpaserver:
    build: .
    container_name: casiplus-hapi-fhir-jpaserver
    restart: on-failure
    depends_on:
      - casiplus-hapi-fhir-db
    ports:
      - ${SERVER_PORT}:8080

  casiplus-hapi-fhir-db:
    image: postgres:9.5
    container_name: casiplus-hapi-fhir-db
    restart: always
    ports:
      - ${POSTGRES_DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data

    volumes:
      - casiplus-hapi-fhir-db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "casiplus_hapi", "-U", "admin" ]
      timeout: 45s
      interval: 10s
      retries: 10

volumes:
  casiplus-hapi-fhir-db:
